name = "education_ems"
main = ".open-next/worker.js" 
compatibility_date = "2026-01-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTJS_ENV = "production"
NEXT_PUBLIC_API_BASE_URL = ""
BACKEND_API_BASE_URL = "http://uems-backend.us-east-1.elasticbeanstalk.com"

[observability]
enabled = true

# THÊM ĐOẠN NÀY: Ép Wrangler build theo định dạng ESM
[build]
command = "npm run build:cf"
