ALTER TABLE Students ADD COLUMN IF NOT EXISTS AdmissionDate DATE NULL;

ALTER TABLE Users ADD COLUMN IF NOT EXISTS EmailConfirmed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS ConfirmationToken VARCHAR(255) NULL;

ALTER TABLE Persons ADD COLUMN IF NOT EXISTS FullNameNoAccent VARCHAR(150) NULL;

ALTER TABLE Employees ADD COLUMN IF NOT EXISTS EmployeeType VARCHAR(20) NULL;