package com.quanlydaotao.backend.scheduling.repository;

import com.quanlydaotao.backend.scheduling.entity.Schedule;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface ScheduleRepository extends JpaRepository<Schedule, UUID> {

    // 🕵️ Kiểm tra trùng phòng
    boolean existsByRoomRoomIdAndSemesterIdAndDayOfWeekAndTimeSlotTimeSlotIdAndScheduleIdNot(
            UUID roomId, UUID semesterId, Integer dayOfWeek, UUID timeSlotId, UUID scheduleId);

    // 🕵️ Kiểm tra trùng lớp
    boolean existsByCourseClassCourseClassIdAndSemesterIdAndDayOfWeekAndTimeSlotTimeSlotIdAndScheduleIdNot(
            UUID courseClassId, UUID semesterId, Integer dayOfWeek, UUID timeSlotId, UUID scheduleId);

    // 🕵️ Kiểm tra trùng giảng viên
    boolean existsByInstructorEmployeeIdAndSemesterIdAndDayOfWeekAndTimeSlotTimeSlotIdAndScheduleIdNot(
            UUID instructorId, UUID semesterId, Integer dayOfWeek, UUID timeSlotId, UUID scheduleId);

    boolean existsByCourseClassCourseClassId(UUID courseClassId);

    @Query("""
            SELECT COALESCE(SUM(COALESCE(s.numberOfPeriods, 0)), 0)
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    Long sumActivePeriodsByCourseClass(@Param("courseClassId") UUID courseClassId);

    @Query("""
            SELECT s
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.isActive = true
              AND s.status = 'AUTO_GENERATED'
            """)
    List<Schedule> findActiveAutoGeneratedByCourseClass(@Param("courseClassId") UUID courseClassId);

    @Query("""
            SELECT s
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus NOT IN ('CANCELLED','ABSENT'))
            """)
    List<Schedule> findActiveBaseSchedulesByCourseClass(@Param("courseClassId") UUID courseClassId);

    @Modifying(clearAutomatically = true, flushAutomatically = true)
    @Query("""
            UPDATE Schedule s
            SET s.isActive = false,
                s.deletedAt = :deletedAt,
                s.status = 'REPLACED_BY_AUTO_REGENERATE',
                s.note = 'Da vo hieu hoa lich goc cu de xep lai tu dong'
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.isActive = true
            """)
    int deactivateActiveSchedulesByCourseClass(
            @Param("courseClassId") UUID courseClassId,
            @Param("deletedAt") LocalDateTime deletedAt);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.room.roomId = :roomId
              AND s.date = :date
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasRoomTimeOverlap(
            @Param("roomId") UUID roomId,
            @Param("date") LocalDate date,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.room.roomId = :roomId
              AND s.date = :date
              AND s.isActive = true
              AND s.scheduleId <> :scheduleId
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasRoomTimeOverlapIgnoringSchedule(
            @Param("roomId") UUID roomId,
            @Param("date") LocalDate date,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime,
            @Param("scheduleId") UUID scheduleId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.date = :date
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND (:ignoredCourseClassId IS NULL OR s.courseClass.courseClassId <> :ignoredCourseClassId)
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasInstructorTimeOverlap(
            @Param("instructorId") UUID instructorId,
            @Param("date") LocalDate date,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime,
            @Param("ignoredCourseClassId") UUID ignoredCourseClassId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.date = :date
              AND s.isActive = true
              AND s.scheduleId <> :scheduleId
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasInstructorTimeOverlapIgnoringSchedule(
            @Param("instructorId") UUID instructorId,
            @Param("date") LocalDate date,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime,
            @Param("scheduleId") UUID scheduleId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.date = :date
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasCourseClassTimeOverlap(
            @Param("courseClassId") UUID courseClassId,
            @Param("date") LocalDate date,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.date = :date
              AND s.isActive = true
              AND s.scheduleId <> :scheduleId
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasCourseClassTimeOverlapIgnoringSchedule(
            @Param("courseClassId") UUID courseClassId,
            @Param("date") LocalDate date,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime,
            @Param("scheduleId") UUID scheduleId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.room.roomId = :roomId
              AND s.semesterId = :semesterId
              AND s.dayOfWeek = :dayOfWeek
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.date IS NULL
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasRecurringRoomConflict(UUID roomId, UUID semesterId, Integer dayOfWeek, UUID timeSlotId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.room.roomId = :roomId
              AND s.semesterId = :semesterId
              AND s.dayOfWeek = :dayOfWeek
              AND s.date IS NULL
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasRecurringRoomTimeOverlap(
            @Param("roomId") UUID roomId,
            @Param("semesterId") UUID semesterId,
            @Param("dayOfWeek") Integer dayOfWeek,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.semesterId = :semesterId
              AND s.dayOfWeek = :dayOfWeek
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.date IS NULL
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasRecurringInstructorConflict(UUID instructorId, UUID semesterId, Integer dayOfWeek, UUID timeSlotId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.semesterId = :semesterId
              AND s.dayOfWeek = :dayOfWeek
              AND s.date IS NULL
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasRecurringInstructorTimeOverlap(
            @Param("instructorId") UUID instructorId,
            @Param("semesterId") UUID semesterId,
            @Param("dayOfWeek") Integer dayOfWeek,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.semesterId = :semesterId
              AND s.dayOfWeek = :dayOfWeek
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.date IS NULL
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasRecurringCourseClassConflict(UUID courseClassId, UUID semesterId, Integer dayOfWeek, UUID timeSlotId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.semesterId = :semesterId
              AND s.dayOfWeek = :dayOfWeek
              AND s.date IS NULL
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND s.timeSlot.startTime < :endTime
              AND :startTime < s.timeSlot.endTime
            """)
    boolean hasRecurringCourseClassTimeOverlap(
            @Param("courseClassId") UUID courseClassId,
            @Param("semesterId") UUID semesterId,
            @Param("dayOfWeek") Integer dayOfWeek,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime);

    List<Schedule> findByCourseClassCourseClassId(UUID courseClassId);
    
    List<Schedule> findByInstructorEmployeeId(UUID instructorId);
    
    List<Schedule> findByRoomRoomId(UUID roomId);

    List<Schedule> findByInstructorEmployeeIdAndDateBetweenAndIsActiveTrueOrderByDateAsc(UUID instructorId, LocalDate fromDate, LocalDate toDate);

    List<Schedule> findByCourseClassCourseClassIdAndDateBetweenAndIsActiveTrueOrderByDateAsc(UUID courseClassId, LocalDate fromDate, LocalDate toDate);

    List<Schedule> findBySemesterIdAndIsActiveTrue(UUID semesterId);

    @Query("""
            SELECT s
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.isActive = true
              AND (s.scheduleType IS NULL OR s.scheduleType = 'FIXED')
              AND (:fromDate IS NULL OR s.date >= :fromDate)
              AND (:toDate IS NULL OR s.date <= :toDate)
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus NOT IN ('CANCELLED','ABSENT'))
            ORDER BY s.date ASC, s.dayOfWeek ASC
            """)
    List<Schedule> findFixedSessions(UUID courseClassId, LocalDate fromDate, LocalDate toDate);

    @Query("""
            SELECT s
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.semesterId = :semesterId
              AND s.isActive = true
              AND (s.scheduleType IS NULL OR s.scheduleType = 'FIXED')
            ORDER BY s.courseClass.classCode ASC, s.date ASC, s.dayOfWeek ASC
            """)
    List<Schedule> findFixedByInstructorAndSemester(UUID instructorId, UUID semesterId);

    @Query("""
            SELECT s
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND (s.scheduleType IS NULL OR s.scheduleType = 'FIXED')
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus NOT IN ('CANCELLED','ABSENT'))
            """)
    Optional<Schedule> findFixedSession(UUID courseClassId, LocalDate date, UUID timeSlotId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND s.scheduleId <> :scheduleId
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasInstructorConflictIgnoringSchedule(
            @Param("instructorId") UUID instructorId,
            @Param("date") LocalDate date,
            @Param("timeSlotId") UUID timeSlotId,
            @Param("scheduleId") UUID scheduleId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.instructor.employeeId = :instructorId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
              AND (:ignoredCourseClassId IS NULL OR s.courseClass.courseClassId <> :ignoredCourseClassId)
            """)
    boolean hasInstructorConflict(UUID instructorId, LocalDate date, UUID timeSlotId, UUID ignoredCourseClassId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.room.roomId = :roomId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND s.scheduleId <> :scheduleId
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasRoomConflictIgnoringSchedule(
            @Param("roomId") UUID roomId,
            @Param("date") LocalDate date,
            @Param("timeSlotId") UUID timeSlotId,
            @Param("scheduleId") UUID scheduleId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.room.roomId = :roomId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasRoomConflict(UUID roomId, LocalDate date, UUID timeSlotId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND s.scheduleId <> :scheduleId
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasCourseClassConflictIgnoringSchedule(
            @Param("courseClassId") UUID courseClassId,
            @Param("date") LocalDate date,
            @Param("timeSlotId") UUID timeSlotId,
            @Param("scheduleId") UUID scheduleId);

    @Query("""
            SELECT COUNT(s) > 0
            FROM Schedule s
            WHERE s.courseClass.courseClassId = :courseClassId
              AND s.date = :date
              AND s.timeSlot.timeSlotId = :timeSlotId
              AND s.isActive = true
              AND (s.scheduleStatus IS NULL OR s.scheduleStatus <> 'CANCELLED')
            """)
    boolean hasCourseClassConflict(UUID courseClassId, LocalDate date, UUID timeSlotId);
}
