// src/constants/studentsInClassData.ts
export const studentsInClassData = [
  {
    id: "HV2408280001",
    name: "Nguyễn Minh Trang",
    phone: "0859051205",
    email: "demo3800@gmail.com",
    studentType: "Học thử",
    class: "test",
    classType: "Offline",
    paymentType: "Thanh toán một lần",
    totalSessions: 2,
    remainingSessions: 0,
  },
  {
    id: "HV260130-1",
    name: "Nguyễn Bảo Châu",
    phone: "0349911063",
    email: "minhdh.6899@gmail.com",
    studentType: "Chính thức",
    class: "test01",
    classType: "Offline",
    paymentType: null,
  },
  {
    id: "HV2408280086",
    name: "Phan Hải Châu",
    phone: "0000003860",
    email: "demo3860@gmail.com",
    studentType: "Chính thức",
    class: "Test",
    classType: "Online",
    paymentType: null,
  },
];
