server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=UniversityManagement;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:Nguyenthongoc123@}
    driver-class-name: ${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          useUnicode: true
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.SQLServerDialect}
  flyway:
    repair-on-migrate: true

# 📝 LOGGING CONFIGURATION
logging:
  level:
    "[org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver]": ERROR
    "[com.quanlydaotao.backend]": DEBUG
    "[org.hibernate.SQL]": INFO
    "[org.hibernate.type.descriptor.sql.BasicBinder]": INFO
open:
  api:
    title: API Quản lý Đào tạo
    description: Tài liệu API cho dự án hệ thống Quản lý Đào tạo
    version: 1.0.0
    serverName: Local Server
    serverUrl: ${OPEN_API_SERVER_URL:/}
