spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: @spring.profiles.active@

# .\mvnw.cmd clean package -DskipTests -P dev
#  java -jar .\target\backend-0.0.1-SNAPSHOT.jar
